version: '3.9'

services:
  db:
    image: postgres:15
    container_name: products_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: product_api
    restart: always
    depends_on:
      - db
    env_file: .env
    ports:
      - "8000:8000"
    command: >
      sh -c "sleep 5 &&
             python -m app.seed &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data:
